name: Build Manager (Spoofed)

on:
  push:
    branches: [ "main", "ci" ]
    paths:
      - '.github/workflows/build-manager.yml'
      - 'manager/**'
      - 'kernel/**'
      - 'userspace/ksud/**'

jobs:
  build-manager:
    uses: ./.github/workflows/build-manager-common.yml
    secrets: inherit
    with:
      spoofed: true